#!/bin/bash

system_type=$(uname -s)

cd "$HOME"
yadm submodule update --recursive --init

function update_mirrorlist() {
	MIRRORLIST='https://archlinux.org/mirrorlist/?country=NL&country=DE&protocol=http&protocol=https&ip_version=4&ip_version=6'
	sudo curl -o /etc/pacman.d/mirrorlist "$MIRRORLIST"
}

function install_packages() {
	echo "Installing packages from .packages"
	yay -S --needed --noconfirm --removemake - < $HOME/.packages
}

function install_arch() {
	echo "Requesting sudo password..."
	sudo -v
	
	read -p "Update mirrorlist? [Y/n]" choice
	case $choice in
		[Yy]* ) update_mirrorlist;;
		[Nn]* ) ;;
		*) ;;
	esac

	sudo sed -i 's/#Server/Server/g' /etc/pacman.d/mirrorlist && sudo pacman -Syu --noconfirm
	sudo sed -i 's/#Color/Color/g' /etc/pacman.conf

	# install yay if missing
	if ! command -v yay > /dev/null 2>&1; then
		echo "Install yay..."
		rm -rf /tmp/yay && \
		  git clone --depth 1 https://aur.archlinux.org/yay-bin.git /tmp/yay && \
		  cd /tmp/yay && \
		  makepkg -si --noconfirm
	fi

	# install packages from .packages file
	read -p "Install packages? [Y/n]" choice
	case $choice in
		[Yn]* ) install_packages;;
		[Nn]* ) ;;
		*) ;;
	esac

	# configure basic firewall
	sudo sed -i 's/IPV6=yes/IPV6=no/' /etc/default/ufw
	sudo ufw default deny
	sudo ufw limit ssh
	sudo ufw enable
	sudo systemctl enable ufw

	# configure mdns
	sudo systemctl enable avahi-daemon
	sudo sed -i -e 's/^\(hosts:.*\)\(resolve.*\)$/\1mdns4_minimal [NOTFOUND=return] \2/' /etc/nsswitch.conf

	# enable profile sync daemon
	systemctl --user enable psd.service

	# enable gdm and network manager
	sudo systemctl enable gdm
	sudo systemctl enable NetworkManager

	# gnome dconf settings
	gsettings set org.gnome.desktop.peripherals.mouse accel-profile 'flat'
	gsettings set org.gnome.desktop.peripherals.touchpad tap-to-click true
	gsettings set org.gnome.desktop.calendar show-weekdate true
	gsettings set org.gnome.desktop.wm.preferences button-layout "appmenu:minimize,maximize,close"
	gsettings set org.gnome.desktop.interface clock-show-date true
	gsettings set org.gnome.shell.overrides dynamic-workspaces false
	gsettings set org.gnome.desktop.wm.preferences num-workspaces "1"
	gsettings set org.gtk.Settings.FileChooser sort-directories-first true
	gsettings set org.gnome.nautilus.preferences default-folder-viewer 'list-view'
	gsettings set org.gnome.nautilus.list-view default-zoom-level 'small'
	gsettings set org.gnome.shell enabled-extensions "['user-theme@gnome-shell-extensions.gcampax.github.com']"
	gsettings set org.gnome.shell.extensions.user-theme name 'Arc-Dark'
	gsettings set org.gnome.desktop.interface gtk-theme 'Arc-Dark'

	# install gnome hidetopbar extension
	EXT_DIR="$HOME/.local/share/gnome-shell/extensions"
	HTB_DIR="hidetopbar@mathieu.bidon.ca"

	## if the extension directory doesn't exist, make it
	if [[ ! -d "${EXT_DIR}" ]]; then
		mkdir -p "${EXT_DIR}"
	fi

	cd "${EXT_DIR}"
	
	if [[ ! -d "${EXT_DIR}/${HTB_DIR}" ]]; then
		git clone https://github.com/mlutfy/hidetopbar.git "${HTB_DIR}"
	fi

	cd "${EXT_DIR}/${HTB_DIR}"
	make
	gnome-extensions enable "${HTB_DIR}"
}

case "$system_type" in
	"Linux")
		install_arch;;
	*)
		echo "Cannot detect the system...";;
esac
